services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: nextapp
    restart: always
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    command: sh -c "cd src && npx prisma migrate deploy && npx prisma db seed && cd .. && npm start"
    networks:
      - app-network
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextapp
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
