name: Lint and type check

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main # Change this to your actual branch

permissions:
  pull-requests: write # Allow commenting on PRs

jobs:
  build-check:
    name: Check npm build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build check
        id: build
        run: |
          npm run build 2> build-error.txt || echo "failed=true" >> $GITHUB_ENV

      - name: Comment on PR if build fails
        if: env.failed == 'true'
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.PAT }}
          script: |
            const fs = require('fs');
            const errorLog = fs.readFileSync('build-error.txt', 'utf8');
            const limitedError = errorLog.length > 5000 ? 
              errorLog.substring(0, 5000) + "\n\n... (error message truncated)" : 
              errorLog;

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ❌ npm build failed\n\n\`\`\`\n${limitedError}\n\`\`\``
            });

            core.setFailed('npm build failed');
